namespace OpenAlBindings.Enums;

public enum AlCStrings
{
	ALC_CAPTURE_DEVICE_SPECIFIER = 0x310,
	ALC_CAPTURE_DEFAULT_DEVICE_SPECIFIER = 0x311,
	ALC_DEFAULT_DEVICE_SPECIFIER = 0x1004,
	ALC_DEVICE_SPECIFIER = 0x1005,
	ALC_DEFAULT_ALL_DEVICES_SPECIFIER = 0x1012,
	ALC_ALL_DEVICES_SPECIFIER = 0x1013,
	AL_VERSION = 0xB002,
}
